### ISSUE TITLE
No pop up during sign in

### ISSUE THREAD

**Issue by reaganh17** [harmony-one/chrome-extension-wallet#93] opened 2021-02-26 21:10 UTC
On my current laptop, while on the site where you sign in with your wallet to stake, https://staking.harmony.one/onewallet, the Sign In button doesn't not pop up the window for the extension. 

![image](https://user-images.githubusercontent.com/67028825/109355313-e379af00-7833-11eb-86e8-2d71091e56d8.png)

I've tried this on both Chrome and Brave, and in incognito modes for both. Also tested with Opera. No browser has this pop up show. The Sign In button simply does nothing.

On my other desktop machine however, the pop up shows up and I am able to sign in without issue.

Both are on Windows 10 and on the latest update, with the latest versions of each browser.

It appears that the inject-script.js does not push in to trigger when the Sign In button is clicked.

Any ideas on what to do here @0xlocker ? Thank you

**Comment by 0xlocker** [comment] 2021-02-26 21:11
@hypnagonia can you help this user? @reaganh17 what onewallet version are you using?

**Comment by reaganh17** [comment] 2021-02-26 21:12
It's the latest version from the Chrome extension store. It's the first time I've used it so I have no trace of the deprecated version on my system.

**Comment by hypnagonia** [comment] 2021-02-27 06:53
@reaganh17 any errors in console?

**Comment by hypnagonia** [comment] 2021-02-27 15:05
could you also reinstall wallet and try again. will it help?

**Comment by reaganh17** [comment] 2021-02-28 01:22
@hypnagonia have tried reinstalling on all browsers, same issue. Restarted many times as well. 
How do I check for errors in the console?

**Comment by reaganh17** [comment] 2021-03-01 19:01
@hypnagonia @0xlocker Just an update here, I did an Inspect and looked at the Console for errors.
Right upon loading of the page for https://staking.harmony.one/onewallet, I get an error for manifest.json:1
It says: Manifest: Line: 1, column: 1, Syntax error.

However I noticed that same error also show up on the main page of https://staking.harmony.one/validators/mainnet

On the https://staking.harmony.one/onewallet page when I click the big Sign In button, there is no actions to the console at all.

**Comment by cristian-smocot** [comment] 2021-03-10 12:04
I am having the exact same issue, Chrome extension v1.1.2

**Comment by vajrasan** [comment] 2021-03-26 02:59
This is not a fix but i found a workaround. If the sign in button doesn't work, you can open another tab and enter the address "chrome-extension://fnnegphlobjdpkhecapkijjdkgcjhkib/popup.html#/login" to accept your wallet and then go back to the sign-in page and click the sign-in button to access the staking website

**Comment by vhsava** [comment] 2021-04-04 21:02
thanks for the workaround, that fixed it for me.

I had the same issue-- the Sign In did nothing : 
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/disable-console.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by medalark** [comment] 2021-04-18 09:43
I have the same problem. What I've found is that in Display Settings (Windows 10) if I have the Scale and layout set to 175%, sign in button does nothing. If I go to 150% or 200% it is fine. 225% also doesn't work for me and I have confirmed this on 2 separate machines.

**Comment by reaganh17** [comment] 2021-05-03 22:47
@medalark that solved my problem! I switched it to 200 to see, and I just saw the bottom of the pop up window. What a bizarre problem! I've never had this on any other site before and I've been on 175% for almost 5 years now. 

Thanks to @vajrasan for the workaround help as well!

**Comment by taqyon** [comment] 2021-05-31 11:49
> @medalark that solved my problem! I switched it to 200 to see, and I just saw the bottom of the pop up window. What a bizarre problem! I've never had this on any other site before and I've been on 175% for almost 5 years now.
> 
> Thanks to @vajrasan for the workaround help as well!

If your problem is no longer relevant, can you please close the issue?

**Comment by prateekj01** [comment] 2022-01-07 11:44
Well I tried to make an account today and the problem still exists

**Comment by prateekj01** [comment] 2022-01-07 11:49
> I have the same problem. What I've found is that in Display Settings (Windows 10) if I have the Scale and layout set to 175%, sign in button does nothing. If I go to 150% or 200% it is fine. 225% also doesn't work for me and I have confirmed this on 2 separate machines.

This worked for me aswell thank you !

**Comment by jakobious** [comment] 2022-03-07 16:46
@reaganh17 @taqyon this issue still happens with Chrome extension! Cannot press the sign in button on staking dashboard, already successfully signed into the wallet

**Comment by jakobious** [comment] 2022-03-07 16:47
Please open and resolve

**Comment by reaganh17** [comment] 2022-03-08 22:20
@jakobious did changing the display scaling change anything?

**Comment by jakobious** [comment] 2022-03-08 22:24
> @jakobious did changing the display scaling change anything?

No, I went to 400% and out to 50% as well, still cannot press the button and sign in, would really like to stake some tokens with some smaller validators to help the decentralization efforts.

**Comment by reaganh17** [comment] 2022-03-08 22:26
@jakobious can you post a screenshot on here so the devs can take a look? be sure to hide any personal info from the screenshot.

**Comment by jakobious** [comment] 2022-03-08 22:32
can you specify what you would like to see in the screen shot? All I am looking at is the sign in button, after it has recognized my extension wallet, not much to see but is what you are referring to?

**Comment by reaganh17** [comment] 2022-03-08 22:35
Yeah just curious at which screen you are not seeing the button. Is it on this area of the site: 
![image](https://user-images.githubusercontent.com/67028825/157337364-ceb31c53-1522-4426-9c5a-8684bb691e04.png)

**Comment by cristian-smocot** [comment] 2022-03-08 22:36
> 

I would use a third party extension like [MathWallet](https://mathwallet.org/en-us/) 
The official extension will be retired anyway when the new official wallet is released.

[ Twitter announcement](https://twitter.com/harmonyprotocol/status/1498424432800538631?t=PaDXu60jvbYI9zND2N6tOQ&s=19)

**Comment by jakobious** [comment] 2022-03-08 22:43
wow - @reaganh17 and @cristian-smocot --- 
this issue occurred yesterday, but I believe changes were made and I am all good now -- I see the chrome extension option was removed, i then used the import address option at the top and I successfully logged into staking dashboard and can access my validators, rewards etc. Thank you very much for communicating actively and for any time/help! 

Great to see these things get resolved.. Now I am looking to switch wallets, is MathWallet the leading and recommended vendor? Id like to assess my options and pick the best substitute

**Comment by cristian-smocot** [comment] 2022-03-08 22:46
> wow - @reaganh17 and @cristian-smocot --- this issue occurred yesterday, but I believe changes were made and I am all good now -- I see the chrome extension option was removed, i then used the import address option at the top and I successfully logged into staking dashboard and can access my validators, rewards etc. Thank you very much for communicating actively and for any time/help!
> 
> Great to see these things get resolved.. Now I am looking to switch wallets, is MathWallet the leading and recommended vendor? Id like to assess my options and pick the best substitute

Some people use Metamask (I don't like it).
I like MathWallet. I am waiting for the release of the new official wallet.
Other people use Guarda wallet.

**Comment by reaganh17** [comment] 2022-03-08 23:16
@jakobious glad you solved the issue, I'll be closing this case again.

**Closed** 2022-03-08 23:16 UTC

**Comment by jakobious** [comment] 2022-03-29 16:54
@reaganh17 can you please help us on this issue: https://github.com/harmony-one/chrome-extension-wallet/issues/115

**Comment by animalinda** [comment] 2024-07-08 23:49
Still is a problem, have been scouring old posts for a fix and this seems to be the most active. Have I missed a step or is there a guide from Math anywhere? I can not solve this and it has been over two weeks unable to claim, withdraw etc

**Comment by animalinda** [comment] 2024-07-09 10:54
Instead of signing into the dashboard before accessing it, find the dashboard first. While signed out of the dashboard click on the math wallet extension and sign into your wallet. Then sign into the dashboard. 
https://docs.harmony.one/home/general/ecosystem/wallets/browser-extensions-wallets/mathwallet/collecting-rewards

**Comment by silva1488** [comment] 2025-07-02 02:37
Hi There,

I'm currently facing the same issue as mentioned above, unable to claim my tokens. Can anyone assist me? Thank you in advance.
